config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
  resources :courses do
    resources :sections, shallow: true do
      resources :lessons do
        resources :comments
        resources :questions do
          resources :answers
        end
      end
    end
  end

  # users
  resources :users

  get '/subscriptions', to: 'subscriptions#all_subscriptions'
  get '/about', to: 'home#about'
  get '/services', to: 'home#services'
  get '/contact', to: 'home#contact'

  # scope subscriptions under course
  resources :courses do
    resources :subscriptions, shallow: true do
      get '/callback' => 'payments#callback'
      post 'payment' => 'payments#create'
      post 'callback' => 'payments#callback'
    end
  end
end

app/models/question.rb
# frozen_string_literal: true

class Question < ApplicationRecord # rubocop:disable Style/Documentation
  has_many :answers

  after_create_commit -> { broadcast_append_to 'questions' }
  after_update_commit -> { broadcast_replace_to 'questions' }
  after_destroy_commit -> { broadcast_remove_to 'questions' }
end

app/controllers/questions_controller.rb
# frozen_string_literal: true

class QuestionsController < ApplicationController # rubocop:disable Style/Documentation
  before_action :set_lesson, only: %i[index new create]

  before_action :set_question, except: %i[index new create]

  def index
    @questions = @lesson.questions
    authorize @questions
  end

  def new
    @question = @lesson.questions.new
    authorize @question
  end

  def create
    @question = @lesson.questions.build(question_params)

    respond_to do |format|
      if @question.save
        # turbo_stream
        flash[:notice] = 'Question created successfully.'
        format.turbo_stream
      else
        render :new
      end
    end
  end

  def show
    authorize @question
  end

  def edit
    authorize @question
  end

  def update
    respond_to do |format|
      if @question.update(question_params)
        flash[:notice] = 'Question updated successfully.'
        format.turbo_stream
      else
        render :edit
      end
    end
  end

  def destroy
    respond_to do |format|
      authorize @question
      
      format.turbo_stream if @question.destroy
    end
  end

  private

  def set_lesson
    @lesson = Lesson.find(params[:lesson_id])
  end

  def question_params
    params.require(:question).permit(:title, :body)
  end

  def set_question
    @question = Question.find(params[:id])
  end
end

app/views/questions/_form.html.erb
<div>
  <%= form_with(model: [lesson, Question.new]) do |form| %>
  
    <div class="my-5">
      <%= form.label :title %>
      <%= form.text_field :title, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
    </div>

    <div class="my-5">
      <%= form.label :body %>
      <%= form.text_field :body, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
    </div>

    <%= link_to 'cancel', lesson_path(@lesson), class: 'inline-block px-4 py-2 leading-none border rounded text-white bg-red-500 hover:bg-red-600 focus:outline-none m-3' %>
    <%= form.submit 'Submit', class: 'inline-block px-4 py-2 leading-none border rounded text-white bg-blue-500 hover:bg-blue-600 focus:outline-none' %>
  <% end %>
</div>

app/views/questions/_question.html.erb
<div>
  <%= question.title %>
</div>

app/views/questions/create.turbo_stream.erb
<%= turbo_stream.append 'questions', partial: 'questions/question', locals: {question: @question} %>
<%= turbo_stream.update Question.new, "" %>

app/views/questions/destroy.turbo_stream.erb
<%= turbo_stream.remove @question %>

app/views/questions/edit.html.erb
<div>
  <%= turbo_frame_tag 'edit-question' do %>
    <h2>Edit question</h2>
    <%# form goes here %>
    <%= form_with(model:@question, method: :patch) do |form| %>
  
      <div class="my-5">
        <%= form.label :title %>
        <%= form.text_field :title, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
      </div>

      <div class="my-5">
        <%= form.label :body %>
        <%= form.text_field :body, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
      </div>

      <%= link_to 'cancel', question_path(@question), class: 'btn btn-sm' %>
      <%= form.submit class: 'btn btn-sm m-3' %>
    <% end %>
  <% end %>
</div>

app/views/questions/index.html.erb
<div>
  <% @questions.each do |question| %>
    <%= link_to question.title, question %>
  <% end %>
</div>

app/views/questions/new.html.erb
<div>
  <%= turbo_frame_tag @question do %>
    <h2>Post a question</h2>

    <%= render 'form', lesson: @lesson, question: @question %>
  <% end %>
</div>

app/views/questions/show.html.erb
<%= turbo_frame_tag 'question' do %>
  <div class="my-2 mx-4">
    <%= render @question %>
  </div>

  <%# edit qn %>
  <div class="mx-6">
    <% if policy(@question).edit? %>
      <%= turbo_frame_tag 'edit-question' do %>
        <%#= link_to 'edit qn', edit_question_path(@question), class: 'btn btn-sm' %>
      <% end %>
    <% end %>
  </div>

  <%# answers %>
  <div class="mx-4">
    <% unless  @question.answers.nil? %>
      <h2 class="underline my-2 mx-4"><%= pluralize(@question.answers.count, 'answer')%></h2>

      <%# broadcast to answers channel %>
      <%= turbo_stream_from 'answers' %>

      <div id='answers' class="mx-4 px-4">
        <% @question.answers.each do |ans| %>
          <div>
            <%= ans.body %>
          </div>
        <% end %>
      </div>
      <div class="my-2 flex justify-end">
        <%# answer the qn %>
        <%= turbo_frame_tag Answer.new %>
        <%= link_to 'ans', new_question_answer_path(@question), class: 'inline-block px-4 py-2 leading-none border rounded text-white bg-blue-500 hover:bg-blue-600 focus:outline-none', data: {turbo_frame: dom_id(Answer.new)} %>
      </div>
    <% end %>
  </div>



<% end %>

app/views/questions/update.turbo_stream.erb
<%= turbo_stream.update @question do %>
  <%= render partial: 'questions/question', locals: {question: @question} %>
<% end %>