config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
  resources :courses do
    resources :sections, shallow: true do
      resources :lessons do
        resources :comments
        resources :questions do
          resources :answers
        end
      end
    end
  end

  # users
  resources :users

  get '/subscriptions', to: 'subscriptions#all_subscriptions'
  get '/about', to: 'home#about'
  get '/services', to: 'home#services'
  get '/contact', to: 'home#contact'

  # scope subscriptions under course
  resources :courses do
    resources :subscriptions, shallow: true do
      get '/callback' => 'payments#callback'
      post 'payment' => 'payments#create'
      post 'callback' => 'payments#callback'
    end
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord # rubocop:disable Style/Documentation
  # track the number of visits for a user
  has_many :visits, class_name: "Ahoy::Visit"

  rolify
  after_create :assign_default_role

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :subscriptions
  has_many :courses, through: :subscriptions
  has_many :payments, through: :subscriptions
  has_many :notifications, as: :recepient

  # check if a user is subscribed to a specified course
  def subscribed_to?(course)
    courses.exists?(course.id)
  end

  def assign_default_role
    return unless roles.blank?

    add_role :student
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController # rubocop:disable Style/Documentation
  before_action :set_user, except: %i[index]
  
  def index
    @pagy, @users = pagy(User.all)
  end

  def edit; end

  def update
    if @user.update(user_params)
      flash[:notice] = 'User updated successfully.'
      redirect_to users_path
    else
      render :edit
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end
end

app/views/users/edit.html.erb
<div class='m-4'>
  <div class="flex justify-center">
    <h3 class="text-xl font-bold mb-4">Edit User</h3>
  </div>

  <strong>Name: </strong><%= @user.name %>
  <%= form_with(model: @user) do |form| %>
    <strong>User Roles: </strong><%= form.collection_check_boxes :role_ids, Role.all, :id, :name %>
    <%= @user.errors[:roles] %>
    <div class='m-3'><%= form.submit class: 'btn btn-sm' %></div>
  <% end %>
</div>

app/views/users/index.html.erb
<div class="flex justify-center">
  <h1 class="text-xl font-bold mb-4">Users</h1>
</div>

<div class="px-8">
  <table class="min-w-full divide-y divide-gray-300">
    <thead>
      <tr>
        <th scope="col" class="py-3 pl-4 pr-3 text-left text-xs font-medium uppercase tracking-wide text-gray-500 sm:pl-0">Name</th>
        <th scope="col" class="px-3 py-3 text-left text-xs font-medium uppercase tracking-wide text-gray-500">Phone</th>
        <th scope="col" class="px-3 py-3 text-left text-xs font-medium uppercase tracking-wide text-gray-500">Role</th>
        <th scope="col" class="px-3 py-3 text-left text-xs font-medium uppercase tracking-wide text-gray-500">courses</th>
      </tr>
    </thead>
    <tbody class="divide-y divide-gray-200 bg-white">
      <% @users.each do |user| %>
        <tr>
          <td class="whitespace-nowrap py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-0"><%= link_to user.name, edit_user_path(user) %></td>
          <td class="whitespace-nowrap py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-0"><%= user.phone %></td>
          <td class="whitespace-nowrap py-4 px-3 text-sm text-gray-500"><%= user.roles.pluck(:name) %></td>
          <td class="whitespace-nowrap py-4 px-3 text-sm text-gray-500"><%= user.courses.count %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<%# subscriptions %>
<div class='px-8 m-3'>
  <%= link_to 'subscriptions', subscriptions_path, class: 'btn btn-sm' %>
</div>