config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
  resources :courses do
    resources :sections, shallow: true do
      resources :lessons do
        resources :comments
        resources :questions do
          resources :answers
        end
      end
    end
  end

  # users
  resources :users

  get '/subscriptions', to: 'subscriptions#all_subscriptions'
  get '/about', to: 'home#about'
  get '/services', to: 'home#services'
  get '/contact', to: 'home#contact'

  # scope subscriptions under course
  resources :courses do
    resources :subscriptions, shallow: true do
      get '/callback' => 'payments#callback'
      post 'payment' => 'payments#create'
      post 'callback' => 'payments#callback'
    end
  end
end

app/models/section.rb
# frozen_string_literal: true

class Section < ApplicationRecord # rubocop:disable Style/Documentation
  belongs_to :course
  has_many :lessons

  validates :title, presence: true, uniqueness: { case_sensitive: false }
end

app/controllers/sections_controller.rb
# frozen_string_literal: true

class SectionsController < ApplicationController # rubocop:disable Style/Documentation
  before_action :set_course, except: %i[show edit update destroy]

  before_action :set_section, only: %i[show edit update destroy]

  def index
    # display all sections belonging to a course
    if @sections.present?
      @pagy, @sections = pagy(subscribed_course.sections, items: 3)
    else
      @pagy, @sections = pagy(@course.sections)
    end
    authorize @sections
  end

  def new
    @section = @course.sections.new
    authorize @section
  end

  def create
    @section = @course.sections.build(section_params)
    
    if @section.save
      redirect_to section_path(@section)
    else
      render :new
    end
  end

  def show
    authorize @section
  end

  def edit
    authorize @section
  end

  def update
    respond_to do |format|
      if @section.update(section_params)
        flash[:notice] = 'Section updated successfully.'
        format.html { redirect_to section_path(@section) }
        format.turbo_stream
      else
        render :edit
      end
    end
  end

  def destroy
    authorize @section
    return unless @section.delete

    flash[:notice] = 'Section deleted.'
    redirect_to root_path
  end

  private

  def set_course
    @course = Course.find(params[:course_id])
  end

  def section_params
    params.require(:section).permit(:title, :description, :course_id)
  end

  def set_section
    @section = Section.find(params[:id])
  end

  def subscribed_course
    current_user.subscriptions.find_by(course_id: params[:course_id])&.course
  end
end

app/views/sections/_form.html.erb
<div class="mx-4">
  <%= form_with(model: [course, Section.new]) do |form| %>
    <% if section.errors.any? %>
      <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
        <h2><%= pluralize(section.errors.count, "error") %> prohibited this section from being saved:</h2>

        <ul>
          <% section.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="my-5">
      <%= form.label :title %>
      <%= form.text_field :title, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
    </div>

      <div class="my-5">
      <%= form.label :description %>
      <%= form.text_field :description, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
    </div>  

    <div class="inline">
      <%= form.submit 'Submit', class: 'inline-block px-4 py-2 leading-none border rounded text-white bg-blue-500 hover:bg-blue-600 focus:outline-none' %>
      <%= link_to 'back', course_path(course), class: 'inline-block px-4 py-2 leading-none border rounded text-white bg-red-500 hover:bg-red-600 focus:outline-none m-3' %>
    </div>
  <% end %>
</div>

app/views/sections/_section.html.erb
<div class="p-4 mx-4">
  <div class="block">
    <h2 class="block text-2xl font-medium mb-2">Course: <%= section.course.title  %></h2>
    <h3 class="block text-xl font-medium mb-2 px-2">Section: <%= section.title %></h3>
    <p class="block text-xl mb-8 px-4">Lessons: <%= section.lessons.count %></p>
  </div>

  <hr class="border-2 mb-4">

  <div class="flex flex-col md:flex-row">
    <div class="w-full md:w-1/3 p-4">
      <div class="bg-white rounded-lg shadow-lg p-4 mb-4">
        <div id="<%= dom_id section %>">
          <div class="my-5 flex items-center">
            <p class="font-medium mr-2">Section Title:</p>
            <p class="text-xl font-medium"><%= section.title %></p>
          </div>

          <div class="my-5 flex items-center">
            <p class="font-medium mr-2">Section Description:</p>
            <p class="text-gray-700"><%= section.description %></p>
          </div>
        </div>
      </div>
      <div class="flex justify-between my-5">
        <% if policy(section).edit? %>
          <%= turbo_frame_tag 'edit-section' do %>
            <%= link_to 'edit', edit_section_path(section), class: 'inline-block px-4 py-2 leading-none border rounded text-white bg-blue-500 hover:bg-blue-600 focus:outline-none' %>
          <% end %>
        <% end %>

        <% if policy(section).destroy? %>
          <%= button_to 'delete', section_path(section), method: :delete, class: 'inline-block px-4 py-2 leading-none border rounded text-white bg-red-500 hover:bg-red-600 focus:outline-none m-3' %>
        <% end %>
      </div>
    </div>
    <div class="w-full md:w-2/3 p-4">
      <div class="bg-gray-200 rounded-lg shadow-lg p-4 mb-4">
        <% if @section.lessons.any? %>
          <div class="">
            <h3 class="text-lg font-bold mb-2"><%= pluralize(@section.lessons.size, 'lesson') %></h3>

            <%= turbo_frame_tag 'lessons' do %>
              <%= link_to 'lessons', section_lessons_path(@section), class: 'inline-block px-4 py-2 leading-none border rounded text-white bg-red-500 hover:bg-red-600 focus:outline-none m-3' %>
            <% end %>
          </div>
        <% end %>
        <% if policy(Lesson.new).new? %>
          <%= turbo_frame_tag 'new-lesson' do %>
            <%= link_to 'new lesson', new_section_lesson_path(section), class: 'inline-block px-4 py-2 leading-none border rounded text-white bg-blue-500 hover:bg-blue-600 focus:outline-none' %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/sections/create.turbo_stream.erb
<%= turbo_stream.append 'sections', partial: 'sections/section', locals: {section: @section} %>
<%= turbo_stream.update Section.new, "" %>

app/views/sections/edit.html.erb
<%= turbo_frame_tag 'edit-section' do %>
  <%= form_with(model: [@section]) do |form| %>
    <% if @section.errors.any? %>
      <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
        <h2><%= pluralize(@section.errors.count, "error") %> prohibited this section from being saved:</h2>

        <ul>
          <% @section.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="my-5">
      <%= form.label :title %>
      <%= form.text_field :title, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
    </div>

      <div class="my-5">
      <%= form.label :description %>
      <%= form.text_field :description, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
    </div>  

    <div class="inline">
      <%= link_to 'cancel', section_url(@section), class: 'inline-block px-4 py-2 leading-none border rounded text-white bg-red-500 hover:bg-red-600 focus:outline-none m-3' %>
      <%= form.submit 'Submit', class: 'inline-block px-4 py-2 leading-none border rounded text-white bg-blue-500 hover:bg-blue-600 focus:outline-none' %>
    </div>
  <% end %>
<% end %>

app/views/sections/index.html.erb
<div class="p-4 mx-4">
  <div class="block">
    <h2 class="block text-2xl font-medium mb-2">Course: <%= @course.title %></h2>
    <h3 class="block text-xl font-medium mb-2 px-2">Sections</h3>
  </div>

  <hr class="border-2 my-4">

  <div class="mx-4 bg-white rounded-lg shadow-lg p-4 mb-4">
    <%= turbo_frame_tag 'sections' do %>
      <div class="m-2">
        <%== pagy_nav(@pagy) %>
      </div>
      <% @sections.each do |section| %>
        <div class="my-2 mx-4 font-lg">
          <strong>Section title: </strong><%= link_to section.title, section %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/sections/new.html.erb
<div class='p-4 m-2'>
    <h2 class='font-bold text-xl'>Course: <%= @course.title %></h2>
    <h3 class='font-bold text-xl'>New section</h3>
    <%= render 'form', course: @course, section: @section %>
</div>

app/views/sections/show.html.erb
<div>
  <%= render @section %>
</div>

app/views/sections/update.turbo_stream.erb
<%= turbo_stream.update @section do %>
  <%= render partial: 'sections/section', locals: {section: @section} %>
<% end %>