config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
  resources :courses do
    resources :sections, shallow: true do
      resources :lessons do
        resources :comments
        resources :questions do
          resources :answers
        end
      end
    end
  end

  # users
  resources :users

  get '/subscriptions', to: 'subscriptions#all_subscriptions'
  get '/about', to: 'home#about'
  get '/services', to: 'home#services'
  get '/contact', to: 'home#contact'

  # scope subscriptions under course
  resources :courses do
    resources :subscriptions, shallow: true do
      get '/callback' => 'payments#callback'
      post 'payment' => 'payments#create'
      post 'callback' => 'payments#callback'
    end
  end
end

app/models/lesson.rb
# frozen_string_literal: true

class Lesson < ApplicationRecord # rubocop:disable Style/Documentation
  belongs_to :section

  has_many :comments, dependent: :destroy

  has_many :questions

  validates :title, presence: true, uniqueness: { case_sensitive: false }

  has_many_attached :videos
  has_many_attached :docs
end

app/controllers/lessons_controller.rb
# frozen_string_literal: true

class LessonsController < ApplicationController # rubocop:disable Style/Documentation
  before_action :set_section, only: %i[index new create]
  before_action :set_lesson, only: %i[show edit update destroy]

  def index
    @pagy, @lessons = pagy(@section.lessons, items: 3)
    authorize @lessons
  end

  def new
    @lesson = @section.lessons.new
    authorize @lesson
  end

  def create
    @lesson = @section.lessons.build(lesson_params)

    respond_to do |format|
      if @lesson.save
        flash[:notice] = 'Lesson created successfully.'
        format.html { redirect_to lesson_path @lesson }
        format.turbo_stream
      else
        render :new
      end
    end
  end

  def show
    authorize @lesson
    console
  end

  def edit
    authorize @lesson
  end

  def update
    respond_to do |format|
      if @lesson.update(lesson_params)
        flash[:notice] = 'Lesson updated.'
        format.html { redirect_to lesson_path @lesson }
        format.turbo_stream
      else
        render :edit
      end
    end
  end

  def destroy
    authorize @lesson
    
    return unless @lesson.delete

    flash[:notice] = 'Lesson deleted.'
    redirect_to root_path
  end

  private

  def set_section
    # lessons are scoped under sections
    @section = Section.find(params[:section_id])
  end

  def set_lesson
    @lesson = Lesson.find(params[:id])
  end

  def lesson_params
    params.require(:lesson).permit(:title, :description, videos: [], docs: [])
  end
end

app/views/lessons/_created_lesson.html.erb
<div id="<%= dom_id lesson %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= lesson.title %>
  </p>
</div>

app/views/lessons/_form.html.erb
<div class="mx-4">
  <%= form_with(model: [section, Lesson.new]) do |form| %>
    <% if lesson.errors.any? %>
      <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
        <h2><%= pluralize(lesson.errors.count, "error") %> prohibited this section from being saved:</h2>

        <ul>
          <% lesson.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="my-5">
      <%= form.label :title %>
      <%= form.text_field :title, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
    </div>

      <div class="my-5">
      <%= form.label :description %>
      <%= form.text_field :description, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
    </div>  

    <div class="my-5">
      <%= form.label :video, "Upload Videos" %>
      <%= form.file_field :video, multiple: true, name: "lesson[videos][]" %>
    </div>

    <div class="my-5">
      <%= form.label :docs, "Upload Docs" %>
      <%= form.file_field :docs, multiple: true, name: "lesson[docs][]" %>
    </div>
    
    <div class="inline">
      <%= link_to 'cancel', section_url(@section), class: 'inline-block px-4 py-2 leading-none border rounded text-white bg-red-500 hover:bg-red-600 focus:outline-none m-3' %>
      <%= form.submit class: 'inline-block px-4 py-2 leading-none border rounded text-white bg-blue-500 hover:bg-blue-600 focus:outline-none' %>
    </div>
  <% end %>
</div>

app/views/lessons/_lesson.html.erb
<div id="<%= dom_id lesson %>" class="p-4 mx-4">
  <div class="block">
    <h2 class="block text-2xl font-medium mb-2">Course: <%= lesson.section.course.title %></h2>
    <h3 class="block text-xl font-medium mb-2 px-2">Section: <%= lesson.section.title %></h3>
    <p class="block text-xl mb-8 px-4">Lesson: <%= lesson.id %></p>
  </div>

  <hr class="border-2 mb-4">

  <div class="flex flex-col md:flex-row">
    <div class="w-full md:w-1/3 p-4">
      <div class="bg-white rounded-lg shadow-lg p-4 mb-4">
        <div>
          <div class="my-5 flex items-center">
            <p class="font-medium mr-2">Lesson Title:</p>
            <p class="text-xl font-medium"><%= lesson.title %></p>
          </div>

          <div class="my-5 flex items-center">
            <p class="font-medium mr-2">Lesson Description:</p>
            <p class="text-gray-700"><%= lesson.description %></p>
          </div>
        </div>
      </div>
      <div>
        <% lesson.docs_attachments.each do |attachment| %>
          # show docs in a list
          # they should be clickable, to expand
        <% end %>
      </div>

      <div class="flex justify-between">
        <p class="my-4">
          <% if policy(lesson).edit? %>
            <%= turbo_frame_tag 'edit-lesson' do %>
              <%= link_to 'edit', edit_lesson_path(lesson), class: 'inline-block px-4 py-2 leading-none border rounded text-white bg-blue-500 hover:bg-blue-600 focus:outline-none' %>
            <% end %>
          <% end %>
        </p>

        <p class="my-4">
          <% if policy(lesson).destroy? %>
            <%= button_to 'delete', lesson_path(lesson), method: :delete, class: 'inline-block px-4 py-2 leading-none border rounded text-white bg-red-500 hover:bg-red-600 focus:outline-none m-3'%>
          <% end %>
        </p>
      </div>
    </div>
    <div class="w-full md:w-2/3 p-4">
      <div class="flex justify-center items-center">
        <% if lesson.videos.attached? %>
          <%# videojs %>
          <video
            id="my-video"
            class="video-js"
            controls
            preload="auto"
            width="640"
            height="264"
            data-setup="{}"
          >
            <% lesson.video_attachments.each do |attachment| %>
              # add animation for the videos
              <source src="<%= url_for(attachment) %>" type="video/mp4" />
            <% end %>
          </video>
        <% else %>
          <p>No video attached.</p>
        <% end %>
      </div>
    </div>
  </div>

  <%# render two cols; comments to the left & qns to the right %>
  <div class="flex flex-col md:flex-row">
    <% if lesson.comments.any? %>
      <div class="w-full md:w-1/2 p-4">
        <h3 class="text-lg p-2">Comments Section</h3>
        <div class="bg-gray-200 rounded-lg shadow-lg p-4 m-4">
          <%= turbo_stream_from 'comments' %>
          <div class="mx-4">
            <% lesson.comments.each do |comment| %>
              <div class="my-2">
                <%= comment.content %>
                <div class="mx-2">
                  by <i><%= comment.user.name %></i> on <i><%= comment.updated_at.utc.strftime('%d-%b-%y') %></i>
                </div>
              </div>
              <%# only comment author can edit the comment %>
              <% if comment.user == current_user %>
                <div class="flex justify-end">
                  <%= turbo_frame_tag 'edit-comment' do %>
                    <div class="flex space-x-4">
                      <%= link_to 'Edit', edit_comment_path(comment), locals: { comment: @comment }, class: 'inline-block px-4 py-2 leading-none border rounded text-white bg-blue-500 hover:bg-blue-600 focus:outline-none' %>
                      <%= button_to 'Delete', comment, method: :delete, data: {turbo_frame: '_top'}, class: 'inline-block px-4 py-2 leading-none border rounded text-white bg-red-500 hover:bg-red-600 focus:outline-none' %>
                    </div>
                  <% end %>
                </div>
          <% end %>
            <% end %>
          </div>
        </div>
        <div id='new-comment' class="m-4">
          <%# render comments/new form %>
          <%= render 'comments/form', locals: { lesson: @lesson} %>
        </div>
      </div>
    <% end %>

    <div class="w-full md:w-1/2 p-4">
      <% if lesson.questions.any? %>
        <h3 class="text-lg p-2">Questions & Answer Section</h3>
        <div class="bg-gray-200 rounded-lg shadow-lg p-4 m-4">
          <%= turbo_stream_from 'questions' %>
          <div id='questions'>

            <% @lesson.questions.each do |question| %>
              <%= turbo_frame_tag 'question' do %>
                <div class="m-2">
                  <%= link_to question.title, question %>
                </div>
              <% end %>
            <% end %>
          </div>
        </div>
      <% end %>
      <div id='new-qn' class="m-4 flex justify-end">
        <%# new qn %>
        <%= turbo_frame_tag Question.new %>
        <%= link_to 'new qn', new_lesson_question_path(@lesson), class: 'inline-block px-4 py-2 leading-none border rounded text-white bg-blue-500 hover:bg-blue-600 focus:outline-none', data: {turbo_frame: dom_id(Question.new)} %>
      </div>
    </div>
  </div>

</div>

app/views/lessons/_updated_lesson.html.erb
<div id="<%= dom_id lesson %>">
  <h3>Lesson</h3>
  
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= lesson.title %>
  </p>

    <p class="my-5">
    <strong class="block font-medium mb-1">Description:</strong>
    <%= lesson.description %>
  </p>

  <p class="my-5"> 
    <strong class="block font-medium mb-1">Video:</strong>
    <% if lesson.video.attached? %>
      <%# videojs %>
      <video
        id="my-video"
        class="video-js"
        controls
        preload="auto"
        width="640"
        height="264"
        poster="MY_VIDEO_POSTER.jpg"
        data-setup="{}"
      >
        <% lesson.video_attachments.each do |attachment| %>
          <source src="<%= url_for(attachment) %>" type="video/mp4" />
        <% end %>
      </video>
    <% else %>
      <p>No video attached.</p>
    <% end %>
    
  </p>

  <p class="my-5">
    <%= turbo_frame_tag 'edit-lesson' do %>
      <%= link_to 'edit', edit_lesson_path(lesson), class: 'btn btn-sm btn-primary' %>
    <% end %>
  </p>

  <p class="my-5">
    <%= button_to 'delete', lesson_path(lesson), method: :delete, class: 'btn btn-sm btn-danger'%>
  </p>

</div>

app/views/lessons/create.turbo_stream.erb
<%= turbo_stream.append 'lessons', partial: 'lessons/created_lesson', locals: {lesson: @lesson} %>
<%= turbo_stream.update 'new-lesson', "" %>

app/views/lessons/edit.html.erb
<div class="mx-4">
  <%= turbo_frame_tag 'edit-lesson' do %>
    <%= form_with(model: [@lesson]) do |form| %>
      <% if @lesson.errors.any? %>
        <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
          <h2><%= pluralize(@lesson.errors.count, "error") %> prohibited this section from being saved:</h2>

          <ul>
            <% @lesson.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="my-5">
        <%= form.label :title %>
        <%= form.text_field :title, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
      </div>

      <div class="my-5">
        <%= form.label :description %>
        <%= form.text_field :description, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
      </div>

      <div class="my-5">
        <%= form.label :video, "Upload Videos" %>
        <%= form.file_field :video, multiple: true, name: "lesson[video][]" %>
      </div>

      <div class="my-5">
        <%= form.label :docs, "Upload Docs" %>
        <%= form.file_field :docs, multiple: true, name: "lesson[docs][]" %>
      </div>
      
      <div class="inline">
        <%= link_to 'cancel', lesson_path(@lesson), class: 'inline-block px-4 py-2 leading-none border rounded text-white bg-red-500 hover:bg-red-600 focus:outline-none m-3' %>
        <%= form.submit 'Submit', class: 'inline-block px-4 py-2 leading-none border rounded text-white bg-blue-500 hover:bg-blue-600 focus:outline-none' %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/lessons/index.html.erb
<div id='lessons'>
  <%= turbo_frame_tag 'lessons' do %>
    <div class='bg-white rounded-lg shadow-lg p-4 mb-4'>
      <%# pagy %>
      <%== pagy_nav(@pagy) %>
      
      <% @lessons.each do |lesson| %>
        <div>
          <%= link_to lesson.title, lesson_path(lesson) %>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/lessons/new.html.erb
<div class="p-4">
  <%= turbo_frame_tag 'new-lesson' do %>
    <h3 class="text-xl font-bold mx-2">New lesson</h3>
    <%= render 'form', section: @section, lesson: @lesson %>
  <% end %>
</div>

app/views/lessons/show.html.erb
<div>
  <%= render @lesson %>
</div>

app/views/lessons/update.turbo_stream.erb
<%= turbo_stream.update @lesson do %>
  <%= render partial: 'lessons/updated_lesson', locals: {lesson: @lesson} %>
<% end %>